# Generated by Django 3.1.4 on 2021-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(null=True, upload_to='img/'),
        ),
        migrations.AlterModelTable(
            name='artist',
            table='Crud_artist',
        ),
    ]
